// test exception
{{ route('test2') }}